<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Xulin Blog</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <?php echo $this->load_category() ?>




                







                <!--                <li class="dropdown">-->
<!--                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">PHP<b class="caret"></b></a>-->
<!--                    <ul class="dropdown-menu">-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">PHP</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Magento</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Zend Framework</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </li>-->
<!---->
<!--                <li class="dropdown">-->
<!--                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Javascript<b class="caret"></b></a>-->
<!--                    <ul class="dropdown-menu">-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Javascript</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Jquery</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">HTML</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">CSS</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">Database</a>-->
<!--                </li>-->
<!---->
<!--                <li class="dropdown">-->
<!--                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Linux<b class="caret"></b></a>-->
<!--                    <ul class="dropdown-menu">-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Desktop</a>-->
<!--                        </li>-->
<!--                        <li>-->
<!--                            <a href="blog-home-2.html">Server</a>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </li>-->
<!---->
<!--                <li>-->
<!--                    <a href="#">Curriculum vitae</a>-->
<!--                </li>-->
<!--                <li>-->
<!--                    <a href="#">TEST</a>-->
<!--                </li>-->
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

