<br />
<br />
<br />
<div class="well">
    <h4>New Posts</h4>
    <div class="row">
        <div class="col-md-12">
            <ul class="list-unstyled">
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
                <li><a href="#">Category Name CateTitle data </a>
                </li>
            </ul>
        </div>
        <!-- /.col-lg-6 -->
    </div>
    <!-- /.row -->
</div>