<style>
    @import url(http://weloveiconfonts.com/api/?family=entypo);
    @import url(http://fonts.googleapis.com/css?family=Roboto);

    /* zocial */
    [class*="entypo-"]:before {
        font-family: 'entypo', sans-serif;
    }

    *,
    *:before,
    *:after {
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }


    h2 {
        color:rgba(255,255,255,.8);
        margin-left:12px;
    }

    body {
        background: #272125;
        font-family: 'Roboto', sans-serif;

    }

    #admin_login {
        position:relative;
        margin: 100px auto;
        width: 380px;
        height: auto;
    }

    input {
        padding: 16px;
        border-radius:7px;
        border:0px;
        background: rgba(255,255,255,.2);
        display: block;
        margin: 15px;
        width: 300px;
        color:white;
        font-size:18px;
        height: 54px;
    }

    input:focus {
        outline-color: rgba(0,0,0,0);
        background: rgba(255,255,255,.95);
        color: #e74c3c;
    }

    #admin_login_button {
        float:right;
        height: 121px;
        width: 50px;
        border: 0px;
        background: #e74c3c;
        border-radius:7px;
        padding: 10px;
        color:white;
        font-size:22px;
    }

    .inputUserIcon {
        position:absolute;
        top:68px;
        right: 80px;
        color:white;
    }

    .inputPassIcon {
        position:absolute;
        top:136px;
        right: 80px;
        color:white;
    }

    input::-webkit-input-placeholder {
        color: white;
    }

    input:focus::-webkit-input-placeholder {
        color: #e74c3c;
    }

</style>
<script>

    $(".user").focusin(function(){
        $(".inputUserIcon").css("color", "#e74c3c");
    }).focusout(function(){
        $(".inputUserIcon").css("color", "white");
    });

    $(".pass").focusin(function(){
        $(".inputPassIcon").css("color", "#e74c3c");
    }).focusout(function(){
        $(".inputPassIcon").css("color", "white");
    });
</script>

<form id="admin_login" method="POST" action="http://www.xulin-tan.de/blog/public/admin/index">
    <h2><span class="entypo-login"></span> Login</h2>
    <button id="admin_login_button" class="submit"><span class="entypo-lock"></span></button>
    <span class="entypo-user inputUserIcon"></span>
    <input type="email" class="user" name="username" placeholder="ursername"/>
    <span class="entypo-key inputPassIcon"></span>
    <input type="password"  name="password" class="pass" placeholder="password"/>
</form>