<div class="row">
    <div class="col-md-4 col-md-offset-5">
        <select id="admin_select_menu" style="height: 40px">
            <option value="php">PHP, Magento, Zend Framework</option>
            <option value="javascript">Javascript, Jquery </option>
            <option value="html">HTML</option>
            <option value="css">CSS</option>
            <option value="database">Database</option>
            <option value="linux">Linux, Server, Desktop</option>
        </select>
    </div>
    <div class="col-md-2 col-md-offset-1">
        <button id="new_post" type="button" class="btn btn-success">Add New Post</button>
    </div>
</div>
<hr />
<div class="row">
    <div id="admin_ajax_content" class="col-md-12">
<?php echo $this->posts; ?>
    </div>
</div>