<input type="hidden" id="pageIndex" value="0" />
<?php
//    $allPosts = $this->allposts->findAllPosts();
//    $contentInUl = '';
//    foreach ($allPosts as $item){
//        $contentInUl .= "<li>
//                            <i class=\"fa fa-plug\" aria-hidden=\"true\"></i> <a><h4>".$item['post_title']."</h4></a><br />
//                            <p class='contentUnderTitle'>
//                                <span class='glyphicon glyphicon-time'></span>
//                                <b>Posted on</b> ".$item['post_create_time']." <b>
//                                   &nbsp;<i class=\"fa fa-tags\" aria-hidden=\"true\"></i>Category:</b>
//                                <a>".$item['post_category']."</a>
//                                    &nbsp;<i class=\"fa fa-user\" aria-hidden=\"true\"></i>
//                                <b>Posted by</b> ".$item['user_name']."</p>
//                        </li><br />";
//    }
?>
<ul>
    <?php echo $this->allposts; ?>
</ul>