<?php
    $allPosts = $this->allposts->findAllPosts();
    print_r($allPosts[0]);
?>
<ul>
    <li>
        <a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdf!!!!!!!!!!!!</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdfsd dfsgdfg</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdfsd </h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsg fdgg qasdas d</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdfsd dfas d</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdsdzaasd dfg fdgg qasdas d</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsadgg qasdas d</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
    <li><a><h4>title titl title title titlevtitletitletitletitletitletitle sdsad sdfsd sdfsd dfs d</h4></a>
        <p><span class="glyphicon glyphicon-time"></span> Posted on August 28, 2013 at 10:00 PM <a>Category: php->magento</a> Posted by Xulin</p>
    </li>
</ul>