<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Xulin '. $this->translate('Blog'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/social_icon/bootstrap-social.css')) ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/terminalEffect/typed.js'))
        ; ?>
<!--        Font Awesome embed code!-->
        <script src="https://use.fontawesome.com/c8fccc7037.js"></script>
    </head>
    <body>
<!--        --><?php //echo $this->_headerView; ?>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://www.xulin-tan.de/blog/public/">Xulin Blog</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php echo $this->load_category() ?>
            </ul>
            <form class="navbar-form navbar-right" method="post" role="search" action="http://www.xulin-tan.de/blog/public/post/index">
                <div class="form-group">
                    <input type="text" class="form-control" name="search_box" placeholder="Xulin">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="container">
            <?php echo $this->content; ?>
            <hr />
<!--            <footer>-->
<!--                <p>&copy; 2016 - --><?php //echo date('Y') ?><!-- by Xulin. --><?php //echo $this->translate('All rights reserved.') ?><!--</p>-->
<!--            </footer>-->


            <footer class="text-center">
                <div class="footer-above">
                    <div class="container">
                        <div class="row">
                            <div class="footer-col col-md-4">
                                <h3>Location</h3>
                                <b> Germany
                                    <br>Leipzig</b>
                            </div>
                            <div class="footer-col col-md-4">
                                <h3>Around the Web</h3>
                                <ul class="list-inline">
                                    <li>
                                        <a href="https://www.facebook.com/xulintan" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                                    </li>
                                    <li>
                                        <a href="http://www.weibo.com/1922372597/profile?topnav=1&wvr=6&is_all=1" class="btn-social btn-outline"><i class="fa fa-fw fa-weibo"></i></a>
                                    </li>
                                    <li>
                                        <a href="https://github.com/fatalerrortan" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="footer-col col-md-4">
                                <h3>About Xulin</h3>
                                <b>Positive, optimistic, humorous</b>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-below">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                Copyright &copy; Xulin Tan 2016
                            </div>
                        </div>
                    </div>
                </div>
            </footer>


        </div> <!-- /container -->
        <?php
            echo $this->inlineScript();
            //echo $this->basePath('test/insertTest.txt');
        ?>

    </body>
</html>
