<br />
<br />
<br />
<div class="col-md-6">
    <div class="well">
        <img src="<?php echo $this->basePath('img/blog/xulin.PNG')?>" class="img-thumbnail" alt="Xulin Profil" width="304" height="236">
    </div>
</div>
<div class="col-md-6">

        <p>Hi, I'm Xulin.I would like to share my experience of learning about programming </p>
    <i class="fa fa-twitter"></i>
    <i class="fa fa-linkedin"></i>
</div>
