<br />
<br />
<br />
<div class="col-md-4">
    <div class="well">
        <img src="<?php echo $this->basePath('img/blog/xulin.PNG')?>" class="img-thumbnail" alt="Xulin Profil" width="304" height="236">
    </div>
</div>
<div class="col-md-6">
    <blockquote>
        <p>
            <?php echo $this->load_homepageWord(); ?>
        </p>
        <footer>Xulin</footer>
    </blockquote>
    <div class="row">
        <div class="col-md-5">
            <a class="btn btn-block btn-social btn-github" href="https://github.com/fatalerrortan">
                <span class="fa fa-github"></span> Sign in with GitHub
            </a>
        </div>
        <div class="col-md-3">
            <a class="fa fa-weibo fa-2x" aria-hidden="true" href="http://www.weibo.com/u/1922372597/home?wvr=5">Weibo</a>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-1">
            <a class="btn btn-social-icon btn-facebook" href="https://www.facebook.com/xulintan">
                <span class="fa fa-facebook"></span>
            </a>
        </div>
        <div class="col-md-5">
            <iframe src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&width=450&layout=standard&action=like&show_faces=true&share=true&height=80&appId" width="450" height="80" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
        </div>
    </div>
</div>
