<br />
<br />
<br />

<div class="row">
    <div class="col-md-8">
        <input type="hidden" id="pageIndex" value="1" />
        <div id ="allPosts" class="well">
            <?php
                echo $this->_allPostsView;
            ?>
        </div>
        <div class="text-center">
            <button id="backward" type="button" class="btn btn-primary"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
            <i class="fa fa-book fa-lg" aria-hidden="true"></i>
            <button id="forward" type="button" class="btn btn-success"><i class="fa fa-arrow-right" aria-hidden="true"></i></button>
        </div>
    </div>
    <div class="col-md-4">
        <?php echo $this->_sidebarView; ?>
    </div>
</div>